### ISSUE TITLE
Facing Difficulty to Run the Project via Command Line in java

### ISSUE THREAD

**Issue by donseenugmail** [javadev/excel-to-json#1]
Configuration is been successfully done and need to run the Project via Command Line and encountering issues such as:
1) [ERROR] Error executing Maven.
[ERROR] The specified user settings file does not exist: /home/shaik/Desktop/Waseem/Untitled

**Comment by javadev** [comment]
Hi,

To build application please use command: `mvn clean package`.
I added start.cmd file with program execution example.

Kind regards, Valentyn
